name: app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  meta: ^1.8.0
  collection: ^1.17.0
  tuple: ^2.0.1
  http: ^0.13.5
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.0.15
  go_router: ^8.0.1
  bloc_concurrency: ^0.2.1
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.1
  font_awesome_flutter: ^10.3.0
  yaml: ^3.1.1
  minio_new: ^1.0.2
  process_run: ^0.13.1
  file_picker: ^5.2.6
  url_launcher: ^6.1.12
  bitsdojo_window: ^0.1.5
  system_tray: ^2.0.3
  launch_at_startup: ^0.2.2
  package_info_plus: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  go_router_builder: ^2.1.1
  build_runner: ^2.4.5
  build_verify: any
  json_serializable: ^6.7.0
  # build_web_compilers: ^3.2.2

  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/cmd/
    - assets/images/
    - assets/images/logo/
    - assets/configs/
